apiVersion: apps/v1
kind: Deployment
metadata:
  name: thousandeyes
  labels:
    app: thousandeyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thousandeyes
  template:
    metadata:
      labels:
        app: thousandeyes
    spec:
      containers:
        - image: turbonomic/thousandeyes
          imagePullPolicy: IfNotPresent
          name: thousandeyes
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: thousandeyes-secrets
              mountPath: /etc/credentials
              readOnly: true
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: thousandeyes-secrets
          secret:
            secretName: "thousandeyes"
            optional: true
        - name: varlog
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: thousandeyes
  labels:
    app: thousandeyes
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: tcp-thousandeyes
  selector:
    app: thousandeyes
